CREATE TABLE Accounts (
    AccountID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(255) NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    Role VARCHAR(50) NOT NULL DEFAULT 'User',
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    Balance DECIMAL(10,2) NOT NULL DEFAULT 0.00
);

CREATE TABLE Transactions (
    TransactionID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    AccountID INT(11) NOT NULL,
    TransactionType VARCHAR(50) DEFAULT NULL,
    Amount DECIMAL(15,2) DEFAULT NULL,
    OldBalance DECIMAL(15,2) DEFAULT NULL,
    NewBalance DECIMAL(15,2) DEFAULT NULL,
    TransactionDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Description TEXT DEFAULT NULL,
    INDEX AccountID (AccountID)
);
